### ISSUE TITLE
duckdb has moved

### ISSUE THREAD

**Issue by jeroen** [fastverse/universe#2]
See https://github.com/r-universe/fastverse/actions/runs/7281778009/job/19842951361

**Comment by jeroen** [comment]
ping @SebKrantz

**Comment by SebKrantz** [comment]
Thanks @jeroen, and sorry for sleeping. I have chose to remove duckdb, because the repo receives very frequent updates (not related to the R package), and I was under the impression that every commit to the repo triggers a new Runiverse build. I wanted to know if this impression was correct, and if it is, whether there is a way to only have changes to subdirectories of large projects trigger new builds (for the sake of the environment etc.).
